### ISSUE TITLE
crash on Ubuntu 

### ISSUE THREAD

**Issue by aguaviva** [PabloMK7/citra#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

citra-linux-appimage-20240516-64e3e9f/citra.AppImage

### Description of Issue

crash, see GDB output

### Expected Behavior

just run as usual

### Reproduction Steps

just run it
```
./citra.AppImage ../0004\ -\ Legend\ of\ Zelda\,\ The\ -\ Ocarina\ of\ Time\ 3D\ \(Europe\)\ \(En\,Fr\,De\,Es\,It\)\ Decrypted.3ds 
```

### Log File

```
>gdb  --args ./citra.AppImage ../0004\ -\ Legend\ of\ Zelda\,\ The\ -\ Ocarina\ of\ Time\ 3D\ \(Europe\)\ \(En\,Fr\,De\,Es\,It\)\ Decrypted.3ds 

[...]

[New Thread 0x7fff6d340640 (LWP 45558)]
[Thread 0x7fff6d340640 (LWP 45558) exited]
[New Thread 0x7fff6d340640 (LWP 45559)]
[Thread 0x7fff6d340640 (LWP 45559) exited]
[  44.746289] Service.NDM <Warning> core/hle/service/ndm/ndm_u.cpp:SuspendScheduler:98: (STUBBED) perform_in_background=false
[  44.746516] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:689: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001

Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:416
416	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:416
#1  0x00007fffecc6dc9c in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#2  0x00007fffec8fe2f0 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#3  0x00007fffec8ffaad in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#4  0x0000555555db169a in ?? ()
#5  0x0000555555daecfd in ?? ()
#6  0x0000555555cc0c00 in ?? ()
#7  0x0000555555cc0418 in ?? ()
#8  0x0000555555cbfd46 in ?? ()
#9  0x0000555555cad1ce in ?? ()
#10 0x00005555559e950b in ?? ()
#11 0x000055555590bcd6 in ?? ()
#12 0x0000555555b09caa in ?? ()
#13 0x0000555555b23790 in ?? ()
#14 0x0000555555b36e43 in ?? ()
#15 0x0000555555b35a7c in ?? ()
#16 0x00007fff7076cc0f in ?? ()
#17 0x00000000000077a4 in ?? ()
#18 0x0000000000007831 in ?? ()
#19 0x3f8000001ff82000 in ?? ()
#20 0x8000000000000000 in ?? ()
#21 0xbf800000005b5108 in ?? ()
#22 0x3f80000043700000 in ?? ()
#23 0x000000000ffff51c in ?? ()
#24 0x0000000000000000 in ?? ()
```

### System Configuration

```
System:
  Host: ThinkCentre Kernel: 6.5.0-35-generic x86_64 bits: 64
    Desktop: GNOME 42.9 Distro: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop System: LENOVO product: 10AAS1MD00 v: ThinkCentre M93p
    serial: <superuser required>
  Mobo: LENOVO model: SHARKBAY v: SDK0E50510 WIN
    serial: <superuser required> UEFI: LENOVO v: FBKTCYAUS date: 03/21/2018
CPU:
  Info: dual core model: Intel Core i5-4570T bits: 64 type: MT MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 933 min/max: 800/3600 cores: 1: 903 2: 943 3: 960
    4: 928
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
    driver: i915 v: kernel
  Display: server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 3840x2160~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 4600 (HSW GT2)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio
    driver: snd_hda_intel
  Device-2: Intel 8 Series/C220 Series High Definition Audio
    driver: snd_hda_intel
  Sound Server-1: ALSA v: k6.5.0-35-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I217-LM driver: e1000e
  IF: eno1 state: down mac: 44:8a:5b:e8:01:99
  Device-2: Ralink MT7610U (Archer T2U 2.4G+5G WLAN Adapter type: USB
    driver: mt76x0u
  IF: wlx8416f9172d51 state: up mac: 84:16:f9:17:2d:51
Drives:
  Local Storage: total: 238.47 GiB used: 22.88 GiB (9.6%)
  ID-1: /dev/sda vendor: Samsung model: MZ7TE256HMHP-000L7 size: 238.47 GiB
Partition:
  ID-1: / size: 233.18 GiB used: 22.88 GiB (9.8%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 434.5 MiB (21.2%) file: /swapfile
Sensors:
  System Temperatures: cpu: 53.0 C mobo: 29.8 C
  Fan Speeds (RPM): cpu: 1824
Info:
  Processes: 273 Uptime: 3h 3m Memory: 7.64 GiB used: 5.4 GiB (70.8%)
  Shell: Bash inxi: 3.3.13
```

**Comment by PabloMK7** [comment]
Hello, can you load the program with gdb so that it has the debug labels in the backtrace?

**Comment by aguaviva** [comment]
Sure, where can I get a build with debug info?

**Comment by PabloMK7** [comment]
Doesn't the app image contain them?

**Comment by aguaviva** [comment]
>Doesn't the app image contain them?
Not sure, I just used your binary, does it have them?

I used this command:
```
>gdb  --args ./citra.AppImage ../0004\ -\ Legend\ of\ Zelda\,\ The\ -\ Ocarina\ of\ Time\ 3D\ \(Europe\)\ \(En\,Fr\,De\,Es\,It\)\ Decrypted.3ds 
```

What should I have used instead?
